### ISSUE TITLE
Locals not working in +server.js page

### ISSUE THREAD

**Issue by gdrose** [pocketbase/js-sdk#151] opened 2023-02-17 15:29 UTC
I've followed the guide to implement pocketbase and sveltekit, and everything is working except for the fact that I cannot use locals and so I cannot access pocketbase in a +server.js POST request route. Any ideas?

**Comment by ganigeorgiev** [comment] 2023-02-17 15:34
Could you provide a little more info what do you mean by _"I cannot use locals"_?

Could you provide a code sample or at least the js error that is thrown in the browser or node console (if any)?

**Comment by ganigeorgiev** [comment] 2023-02-17 15:40
I'm still not sure that I understand what do you mean. What is `local.user` supposed to be?

The [SSR SvelteKit example](https://github.com/pocketbase/js-sdk#ssr-integration) uses `locals.pb` which is an instance of the SDK client. To access the authenticated user model (if any), you can do it from `locals.pb.authStore.model`.

If that's not what you are asking, please provide a little more context.

**Comment by gdrose** [comment] 2023-02-17 16:00
Sorry for not being clear. I've set the authStore model into a user variable in locals for simplicity. However this doesn't really matter because even if in all other pages the locals.pb.authStore.model is working, in the POST request is returning null and every other method of locals.pb is returning undefined or empty arrays.

`	console.log(locals.pb.authStore.model); // Logging NULL even though in the other routes is perfectly fine

await locals.pb.collection('test1').getFullList(200) // Returning empty array even though is not empty


`

**Comment by ganigeorgiev** [comment] 2023-02-17 16:11
If `locals.pb.authStore.model` is `null` then this means that the request client is not authenticated.
This is also the reason why `getFullList()` returns and empty array (most likely your `test1` collection "List/Search API rule" requires authentication).

But once again, you are not providing enough context to help you debug it and I'm not able to reproduce the issue.

If I follow the [SSR example](https://github.com/pocketbase/js-sdk#ssr-integration) with a brand new SvelteKit project (aka. `npm create svelte@latest my-app`), I'm able to access the authenticated state in a server-side POST handler if the auth state was previously loaded from a cookie in the `hook.server.js`.

I'll close the issue for now, but feel free to provide a minimal reproducible repo and I'll investigate it.

**Closed by ganigeorgiev** 2023-02-17 16:11 UTC

**Comment by gdrose** [comment] 2023-02-17 16:19
The +server.js is a stripe webhook, basically it listens for a charge succeeded. What I want to do is update the user fields after the payment is completed inside the webhook. 
```

import Stripe from 'stripe';
import { SECRET_STRIPE_KEY, STRIPE_WEBHOOK_SECRET } from '$env/static/private';

const stripe = new Stripe(SECRET_STRIPE_KEY);

export async function POST({ request, locals, cookies }) {
	const body = await request.text();
	const signature = request.headers.get('stripe-signature');
	let event;

	try {
		event = stripe.webhooks.constructEvent(body, signature, STRIPE_WEBHOOK_SECRET);
	} catch (err) {
		console.warn("⚠️  Webhook signature verification failed.", err.message);

		return new Response(undefined, { status: 400 });
	}

	if (event.type == 'charge.succeeded') {
		const charge = event.data.object;

		console.log(event);

		// use locals.pb to edit user field

		console.log("✅ Charge succeeded ${charge.id}");
	}	

	return new Response(undefined);
}
```

**Comment by ganigeorgiev** [comment] 2023-02-17 16:36
I understand now.

The reason why `locals.pb.authStore.model` is empty inside your POST action is because it is triggered not from the user but from other external client (in this case Stripe) and since the PocketBase SDK is initialized in `hook.server.js`, there is no cookie token associated with the request and the AuthStore will be empty.

This is not PocketBase specific. Usually in this type of situation you need to authenticate as "admin" and update the user state with the result of your Stripe handling.
To do that you can create a new SDK instance inside your action, eg:

```js
export async function POST({ request, locals}) {
    const pb = new PocketBase("http://127.0.0.1");
    pb.admins.authWithPassword("test@example.com", "1234567890") // could be loaded from env variables

    // use the admin client as usual
    const result = pb.collection("example").getFullList();

    ...
}
```

_Technically you can also use `locals.pb` client to authorize as admin but to avoid accidentally leaking the admin token to the user in case of a redirect or similiar, it is "safer" to initialize a one-off admin client._
