### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/pocketbase/dist/pocketbase.es.mjs not supported.

### ISSUE THREAD

**Issue by RyanB28** [pocketbase/js-sdk#34] opened 2022-09-17 20:11 UTC
The title says almost all. I am using ESM.
Package.json 
`{
  "name": "NotNeeded",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start:dev": "npx ts-node ./src/index.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/puppeteer": "^5.4.6",
    "pocketbase": "^0.7.0",
    "puppeteer": "^17.1.3"
  },
  "devDependencies": {
    "typescript": "^4.8.3"
  }
}
`

tsconfig.json
`
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
    // "incremental": true,                              /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
    // "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */
    // "tsBuildInfoFile": "./.tsbuildinfo",              /* Specify the path to .tsbuildinfo incremental compilation file. */
    // "disableSourceOfProjectReferenceRedirect": true,  /* Disable preferring source files instead of declaration files when referencing composite projects. */
    // "disableSolutionSearching": true,                 /* Opt a project out of multi-project reference checking when editing. */
    // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */

    /* Language and Environment */
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    // "lib": [],                                        /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    // "jsx": "preserve",                                /* Specify what JSX code is generated. */
    // "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */
    // "emitDecoratorMetadata": true,                    /* Emit design-type metadata for decorated declarations in source files. */
    // "jsxFactory": "",                                 /* Specify the JSX factory function used when targeting React JSX emit, e.g. 'React.createElement' or 'h'. */
    // "jsxFragmentFactory": "",                         /* Specify the JSX Fragment reference used for fragments when targeting React JSX emit e.g. 'React.Fragment' or 'Fragment'. */
    // "jsxImportSource": "",                            /* Specify module specifier used to import the JSX factory functions when using 'jsx: react-jsx*'. */
    // "reactNamespace": "",                             /* Specify the object invoked for 'createElement'. This only applies when targeting 'react' JSX emit. */
    // "noLib": true,                                    /* Disable including any library files, including the default lib.d.ts. */
    // "useDefineForClassFields": true,                  /* Emit ECMAScript-standard-compliant class fields. */
    // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */

    /* Modules */
    "module": "commonjs",                                /* Specify what module code is generated. */
    // "rootDir": "./",                                  /* Specify the root folder within your source files. */
    // "moduleResolution": "node",                       /* Specify how TypeScript looks up a file from a given module specifier. */
    // "baseUrl": "./",                                  /* Specify the base directory to resolve non-relative module names. */
    // "paths": {},                                      /* Specify a set of entries that re-map imports to additional lookup locations. */
    // "rootDirs": [],                                   /* Allow multiple folders to be treated as one when resolving modules. */
    // "typeRoots": [],                                  /* Specify multiple folders that act like './node_modules/@types'. */
    // "types": [],                                      /* Specify type package names to be included without being referenced in a source file. */
    // "allowUmdGlobalAccess": true,                     /* Allow accessing UMD globals from modules. */
    // "moduleSuffixes": [],                             /* List of file name suffixes to search when resolving a module. */
    // "resolveJsonModule": true,                        /* Enable importing .json files. */
    // "noResolve": true,                                /* Disallow 'import's, 'require's or '<reference>'s from expanding the number of files TypeScript should add to a project. */

    /* JavaScript Support */
    // "allowJs": true,                                  /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
    // "checkJs": true,                                  /* Enable error reporting in type-checked JavaScript files. */
    // "maxNodeModuleJsDepth": 1,                        /* Specify the maximum folder depth used for checking JavaScript files from 'node_modules'. Only applicable with 'allowJs'. */

    /* Emit */
    // "declaration": true,                              /* Generate .d.ts files from TypeScript and JavaScript files in your project. */
    // "declarationMap": true,                           /* Create sourcemaps for d.ts files. */
    // "emitDeclarationOnly": true,                      /* Only output d.ts files and not JavaScript files. */
    // "sourceMap": true,                                /* Create source map files for emitted JavaScript files. */
    // "outFile": "./",                                  /* Specify a file that bundles all outputs into one JavaScript file. If 'declaration' is true, also designates a file that bundles all .d.ts output. */
    // "outDir": "./",                                   /* Specify an output folder for all emitted files. */
    // "removeComments": true,                           /* Disable emitting comments. */
    // "noEmit": true,                                   /* Disable emitting files from a compilation. */
    // "importHelpers": true,                            /* Allow importing helper functions from tslib once per project, instead of including them per-file. */
    // "importsNotUsedAsValues": "remove",               /* Specify emit/checking behavior for imports that are only used for types. */
    // "downlevelIteration": true,                       /* Emit more compliant, but verbose and less performant JavaScript for iteration. */
    // "sourceRoot": "",                                 /* Specify the root path for debuggers to find the reference source code. */
    // "mapRoot": "",                                    /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,                          /* Include sourcemap files inside the emitted JavaScript. */
    // "inlineSources": true,                            /* Include source code in the sourcemaps inside the emitted JavaScript. */
    // "emitBOM": true,                                  /* Emit a UTF-8 Byte Order Mark (BOM) in the beginning of output files. */
    // "newLine": "crlf",                                /* Set the newline character for emitting files. */
    // "stripInternal": true,                            /* Disable emitting declarations that have '@internal' in their JSDoc comments. */
    // "noEmitHelpers": true,                            /* Disable generating custom helper functions like '__extends' in compiled output. */
    // "noEmitOnError": true,                            /* Disable emitting files if any type checking errors are reported. */
    // "preserveConstEnums": true,                       /* Disable erasing 'const enum' declarations in generated code. */
    // "declarationDir": "./",                           /* Specify the output directory for generated declaration files. */
    // "preserveValueImports": true,                     /* Preserve unused imported values in the JavaScript output that would otherwise be removed. */

    /* Interop Constraints */
    // "isolatedModules": true,                          /* Ensure that each file can be safely transpiled without relying on other imports. */
    // "allowSyntheticDefaultImports": true,             /* Allow 'import x from y' when a module doesn't have a default export. */
    "esModuleInterop": false,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    // "preserveSymlinks": true,                         /* Disable resolving symlinks to their realpath. This correlates to the same flag in node. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    /* Type Checking */
    "strict": true,                                      /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                            /* Enable error reporting for expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,                         /* When type checking, take into account 'null' and 'undefined'. */
    // "strictFunctionTypes": true,                      /* When assigning functions, check to ensure parameters and the return values are subtype-compatible. */
    // "strictBindCallApply": true,                      /* Check that the arguments for 'bind', 'call', and 'apply' methods match the original function. */
    // "strictPropertyInitialization": true,             /* Check for class properties that are declared but not set in the constructor. */
    // "noImplicitThis": true,                           /* Enable error reporting when 'this' is given the type 'any'. */
    // "useUnknownInCatchVariables": true,               /* Default catch clause variables as 'unknown' instead of 'any'. */
    // "alwaysStrict": true,                             /* Ensure 'use strict' is always emitted. */
    // "noUnusedLocals": true,                           /* Enable error reporting when local variables aren't read. */
    // "noUnusedParameters": true,                       /* Raise an error when a function parameter isn't read. */
    // "exactOptionalPropertyTypes": true,               /* Interpret optional property types as written, rather than adding 'undefined'. */
    // "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
    // "noFallthroughCasesInSwitch": true,               /* Enable error reporting for fallthrough cases in switch statements. */
    // "noUncheckedIndexedAccess": true,                 /* Add 'undefined' to a type when accessed using an index. */
    // "noImplicitOverride": true,                       /* Ensure overriding members in derived classes are marked with an override modifier. */
    // "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type. */
    // "allowUnusedLabels": true,                        /* Disable error reporting for unused labels. */
    // "allowUnreachableCode": true,                     /* Disable error reporting for unreachable code. */

    /* Completeness */
    // "skipDefaultLibCheck": true,                      /* Skip type checking .d.ts files that are included with TypeScript. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
`

The full error is 
`
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/pocketbase/dist/pocketbase.es.mjs not supported.
Instead change the require of .../node_modules/pocketbase/dist/pocketbase.es.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (.../TheScraper/src/controller/pocketbaseController.ts:12:22)
    at m._compile (/opt/homebrew/lib/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (.../TheScraper/src/index.ts:12:32)
    at m._compile (/opt/homebrew/lib/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:54:12)
    at main (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
`

Am I doing something wrong? Or is it a bug?

**Comment by ganigeorgiev** [comment] 2022-09-17 20:17
If you want to use the es bundle you need to add a `"type": "module"` in your package.json.

If you want to use the common js bundle you have to import it like this (note the `/cjs` path):

```js
const PocketBase = require('pocketbase/cjs');
```

IF you are using an older node version, you may also need to load some polyfills. You could find more info in the "Installation" section - https://github.com/pocketbase/js-sdk#installation.

**Comment by ganigeorgiev** [comment] 2022-09-18 07:34
@RyanB28 I'll close the issue since the above should allow you to load the sdk as commonjs module (although I recommend to use the ES bundle because you'll be able to use also the other exports like the DTOs).

If you are still unable resolve the issue, please comment with your node version and how you load the SDK and II'll investigate it further.

**Closed by ganigeorgiev** 2022-09-18 07:34 UTC

**Comment by RyanB28** [comment] 2022-09-18 10:57
> If you want to use the es bundle you need to add a `"type": "module"` in your package.json.
> 
> If you want to use the common js bundle you have to import it like this (note the `/cjs` path):
> 
> ```js
> const PocketBase = require('pocketbase/cjs');
> ```
> 
> If you are using an older node version, you may also need to load some polyfills. You could find more info in the "Installation" section - https://github.com/pocketbase/js-sdk#installation.

If I add Type Module, I get "TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"".

**Comment by ganigeorgiev** [comment] 2022-09-18 11:06
@RyanB28 Ah, I see. You may need to configure your ts compiler options per https://github.com/TypeStrong/ts-node/issues/1007, so something like this may work (_I didn't tested it_):

```
{
  ...,
  "compilerOptions": {
    "module": "esnext"
  }
}
```

Or you can also refer to this SO answer - https://stackoverflow.com/questions/62096269/cant-run-my-node-js-typescript-project-typeerror-err-unknown-file-extension#answer-71426203.

Using the CommonJS module is fine, but keep in mind that a lot of new packages are moving to ESM (even browsers now supports them) and you may not be able to use them.

**Comment by RyanB28** [comment] 2022-09-18 11:32
> @RyanB28 Ah, I see. You may need to configure your ts compiler options per [TypeStrong/ts-node#1007](https://github.com/TypeStrong/ts-node/issues/1007), so something like this may work (_I haven't tested it_):
> 
> ```
> {
>   ...,
>   "compilerOptions": {
>     "module": "esnext"
>   }
> }
> ```
> 
> Or you can also refer to this SO answer - https://stackoverflow.com/questions/62096269/cant-run-my-node-js-typescript-project-typeerror-err-unknown-file-extension#answer-71426203.
> 
> Using the CommonJS module is fine, but keep in mind that a lot of new packages are moving to ESM (even browsers now supports them) and you may not be able to use them.

You are a HERO! Thank you

**Comment by Megajin** [comment] 2022-12-23 21:34
**For anyone flying by for the lookout of a quickfix:**

In my case I was working in a nx-monorepo where this problem destroyed my precious time. No fixes helped like changing the `tsconfig.json` or `package.json` (btw. if you are in a integrated monorepo there will be no package.json). Anyway Webpack was causing this and I was not accepting the option to create a custom webpack config (which in most cases will cause other problems). 

Here is my quick and somewhat dirty option:

1. Locate Pocketbase in your `node_modules` folder
_if you are using yarn with Plug & Play you have to add a `.yarnrc.yml` in the root of your project and add this line to it: `nodeLinker: node-modules`. Delete the folder `.yarn` and all pnp related files. After that a clean `yarn install`_

2. Open the `package.json`

3. Change the part `"exports"`of your `package.json` from this:
```json
    "exports": {
        ".": "./dist/pocketbase.es.mjs",
        "./cjs": "./dist/pocketbase.cjs.js",
        "./umd": "./dist/pocketbase.umd.js"
    }
```
to this:
```json
    "exports": {
        ".": "./dist/pocketbase.cjs.js",
        "./cjs": "./dist/pocketbase.cjs.js",
        "./umd": "./dist/pocketbase.umd.js"
    }
```
_If you dont do this and just to import pocketbase like this `import PocketBase from 'pocketbase/dist/pocketbase.cjs.js` your Typescript linter will slap you in the face for it._

**Important:** If you update your packages you will probably do this again.

I know this is not ideal. However in my situation I was not able to go for `"NodeNext"` and `"type": "module"`.  This whole Webpack,Rollup,Vite,TSDX,NX,etc. stuff is pure madness 😅.

**Comment by Daynil** [comment] 2023-03-12 16:25
Thanks for that @Megajin, that solved my issue too.

I'm using this with nextjs, and everything was working fine importing from the ESM version. However, I also run some administrative scripts using ts-node, and for some reason ts-node has huge issues with this, even though nextjs was totally fine and was using the same tsconfig and package.json. It's crazy black magic this ESM business.

For anyone wanting to reference it, here is the ts-node issue (though no amount of tinkering with the suggested solutions/workarounds fixed it for me):
https://github.com/TypeStrong/ts-node/issues/935

**Comment by mikolertesx** [comment] 2024-07-31 00:59
Would be really useful to get an actual long term solution, it's still an issue to me :d.
had the same issue as him https://github.com/pocketbase/js-sdk/issues/34#issuecomment-1364348123
But the issue is that I was trying to run this inside a NestJS app that doesn't have an export thingy.

😢 It is what it is.

**Comment by ganigeorgiev** [comment] 2024-07-31 01:52
@mikolertesx I don't think this is something PocketBase should deal with. All JS runtimes (including browsers) are moving to ESM and there are no plans to change the exports to the CJS bundle (in fact in future versions I'm considering removing them entirely). If you think that there is something that can be done in PocketBase to solve yours and other more general case, then feel free to open a PR and I'll consider it.
