### ISSUE TITLE
Expand not working on search

### ISSUE THREAD

**Issue by Calemy** [pocketbase/js-sdk#121] opened 2022-12-28 12:53 UTC
i use the expand attribute on the option but i don't get anything in the expand object

Example:

```js
import pb from "../helper/database.js"

(async () => {
    const record = await pb.collection('scores').getList(1, 50, {
        sort: 'created',
        expand: 'user',
      });

    console.log(record)
})();
```
this is the response i get

```js
g {
  page: 1,
  perPage: 50,
  totalItems: 1,
  totalPages: 1,
  items: [
    n {
      beatmap: 1,
      collectionId: 'y2d1ky9qk5bk7hc',
      collectionName: 'scores',
      created: '2022-12-28 12:48:37.592Z',
      id: 'bw7tq4fb8m4tlmg',
      updated: '2022-12-28 12:48:37.592Z',
      user: 'pcvczpusxeosj6p',
      expand: {}
    }
  ]
}
```

this is the collection record
![grafik](https://user-images.githubusercontent.com/45440100/209815345-e5d868f3-4d3a-4b6c-8b83-ca54098dbc72.png)

am i doing something wrong?

**Comment by ganigeorgiev** [comment] 2022-12-28 12:57
_If you haven't already, please check https://pocketbase.io/docs/expanding-relations/._

You need to have "View API" rule permission for the relation(s) you want to expand. Or in other words, make sure that your `users` "View API" rule is properly configured.

**Comment by ganigeorgiev** [comment] 2022-12-29 09:12
I'm closing the issue since I'm not able to reproduce it locally.

@Calemy if you are still experiencing it, please provide more details and I'll investigate it.

**Closed by ganigeorgiev** 2022-12-29 09:12 UTC
