### ISSUE TITLE
Getting 404 on authWithPassword

### ISSUE THREAD

**Issue by flomero** [pocketbase/js-sdk#128] opened 2023-01-11 15:38 UTC
I can't get Auth to work with Sveltekit and SSR. somehow the SDK sends a GET Request and always gets a 404 Response instead of a POST request sending the Login Information to the PB Server. might be an error on my side but I used the example code and tried it in a new empty project. 

ID | nj9haogk3biddth
-- | --
Status | 404
Method | GET
Auth | guest
URL | /api/collections/users/auth-with-password
Referer | N/A
Remote IP | 172.20.0.2
User IP | xxx
UserAgent | undici
Meta | {   "errorDetails": "<nil>",   "errorMessage": "Not Found" }
Created | 2023-01-1115:33:59 UTC

**Comment by ganigeorgiev** [comment] 2023-01-11 15:45
Are you sure that you are looking at the related access log?

The SDK `authWithPassword` is sending `POST`: https://github.com/pocketbase/js-sdk/blob/b123521190adccdfa7c294dad7ecc3d48abe29b3/src/services/RecordService.ts#L271-L287

Could you provide a code sample how you are sending the request?

What version of the SDK and PocketBase you are using?

**Comment by flomero** [comment] 2023-01-11 15:53
yes the details above are from the related access log. i tried SDK Versions 0.9.1 and 0.10,0 and Pocketbase Version 0.11.0

**Comment by ganigeorgiev** [comment] 2023-01-11 15:57
I'm not able to reproduce it. I've even tested yesterday the SSR examples with the latest SvelteKit and it is working fine.

Could you provide a minimal reproducible repo? It is possible that this could be cause by the `fetch` polyfill (from the useragent "undici"; I think it comes with SvelteKit). If you are using an older node version, try upgrading to Node 18.

**Comment by ganigeorgiev** [comment] 2023-01-11 16:09
Another possible reason could be if you have a reverse proxy (eg. nginx) that overwrite/redirect the request.

**Comment by flomero** [comment] 2023-01-11 16:53
okay well, I figured it out:
the requests work fine in both client-side and server-side Sveltekit Code if they are sent to an HTTPS address. somehow if the base URL is just HTTP it still works fine client side (what I used first) but stops working in SSR environment. HTTPS fixes it but i still can't figure out why. 
I also tried both ways in Thunderclient manually without the SDK and they both work fine, so it shouldn't be the proxy

**Comment by ganigeorgiev** [comment] 2023-01-11 17:15
I'm not sure how to reproduce it but I don't think this is related to the SDK. I've just verified it and it is working fine locally. I did the following:

1. Created a new skeleton SvelteKit project: `npm create svelte@latest test_128`
2. Added the SDK as dependency: `npm install pocketbase --save-dev`
3. "Copy-paste"-ed the SSR SvelteKit example from the readme.
4. Started the dev server: `npm run dev`

I've tested with sending `authWithPassword()` and `getList()` calls and in both cases it worked fine (I'm using Node v18.10.0 and connecting directly to a local PocketBase instance, aka. there are no proxies, docker/vagrant virtualization, etc.). 

I guess this could be caused by:
- proxy misconfiguration (eg. http -> https redirect)
- environment specific setting related to the [svelte node adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-node#environment-variables)
- bug/incomplete implementation in the `fetch` polyfill (another user has reported in the past an issue with the unidici client in https://github.com/pocketbase/pocketbase/discussions/278#discussioncomment-3356869)
- Something totally else

I'll close the issue for now because I don't think this is related to the SDK, but if you've managed to identify the source of the issue and think it is a bug in PocketBase, please let me know and I'll investigate in more thoroughly.

**Closed by ganigeorgiev** 2023-01-11 17:15 UTC

**Comment by flomero** [comment] 2023-01-11 17:24
thanks for the quick response and help. I'll let you know if I find out what caused the problem

**Comment by hsedr** [comment] 2023-01-14 14:25
I am experiencing the same problem here. Every request to the api returns status code 404.

**Comment by ganigeorgiev** [comment] 2023-01-14 14:35
@hsedr Please open a new issue with more information about your setup and what you are doing. Code sample/minimal reproducible repo will be also helpful.
