### ISSUE TITLE
Failed to request email change

### ISSUE THREAD

**Issue by dimplast** [pocketbase/js-sdk#97] opened 2022-12-03 17:54 UTC
I try to build a simple sveltekit app to manage a user account.
I have implemented register, login, logout and now 

i try to update username, email and password.

but when i use requestEmailChange 

`try {`
`	await locals.pb.collection('users').requestEmailChange('newmail@hello.com');`
`} catch (err) {`
   `console.log(err)`
`}`

i take this error:

ClientResponseError 400: Failed to request email change.
    at new i (file:///C:/Users/dimitris/mypocket/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2078)
    at file:///C:/Users/dimitris/mypocket/node_modules/pocketbase/dist/pocketbase.es.mjs:1:36224
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateEmail (/src/routes/my/settings/account/+page.server.js:11:4)
    at async handle_action_json_request (file:///C:/Users/dimitris/mypocket/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:42:16)
    at async resolve (file:///C:/Users/dimitris/mypocket/node_modules/@sveltejs/kit/src/runtime/server/index.js:247:17)
    at async Object.handle (/C:\Users\dimitris\mypocket\src\hooks.server.js:20:19)
    at async respond (file:///C:/Users/dimitris/mypocket/node_modules/@sveltejs/kit/src/runtime/server/index.js:298:20)
    at async file:///C:/Users/dimitris/mypocket/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:423:22 {
  url: 'http://127.0.0.1:8090/api/collections/users/request-email-change',
  status: 400,
  data: { code: 400, message: 'Failed to request email change.', data: {} },
  isAbort: false,
  originalError: null

**Comment by ganigeorgiev** [comment] 2022-12-03 18:25
@dimplast The request could fail because:

- the new email is already registered

- failed to send the email to the new address


You can find a more detailed errors in the Admin UI > Logs and/or enable debug stdout logs using the `--debug` flag.

Make sure that your mail settings are properly configured. You can also try sending test emails in the Admin UI > Mail settings > Send test emails.
Please note that by default PocketBase uses the unix `sendmain` command which is not available on all platforms.
For test purposes I usually use [mailtrap.io](https://mailtrap.io/). They have free plans and provide a "fake" SMTP server with mail preview.

**Comment by ganigeorgiev** [comment] 2022-12-05 07:06
I'm closing the issue since I can't reproduce it.

My guess is that the `requestEmailChange` fails to send the email. As mentioned in the previous comment, you could try mailtrap.io and enabling the SMTP settings from the Admin UI.

If you are still having difficulties making it work, please let me know and I'll investigate it more thoroughly.

**Closed by ganigeorgiev** 2022-12-05 07:06 UTC

**Comment by dimplast** [comment] 2022-12-07 11:11
@ganigeorgiev Thank you so much for your help. i followed your advice and i used mailtrap.io. Now requestEmailChange works perfect. 
Thank again.
