### ISSUE TITLE
cant get cookies on mobile

### ISSUE THREAD

**Issue by Marius555** [pocketbase/js-sdk#245] opened 2023-10-01 13:36 UTC
im using pocketbase.io together with next 13.5, im trying to get cookies from mobile device but its seems im unable...its strange because from desktop everything is ok, but from phone nothing....i try to change httpOnly: true or false, im still getting the same...

**Comment by ganigeorgiev** [comment] 2023-10-01 13:48
It seems to be environment specific but without any details or information about your deployment setup and how you are accessing it on the phone, I'm not sure how to help.

I'll close the issue as I don't think it is JS SDK related, but if you think otherwise please at least provide some code sample and/or reproducible steps.

**Closed by ganigeorgiev** 2023-10-01 13:48 UTC

**Comment by Marius555** [comment] 2023-10-01 13:58
this is my server component using server actions 
`const result = await LoginSchema.isValid(await data)
    if (result === true) {
        try {
            const dota_resp = await pb.collection('UserTable').authWithPassword(await data.Email, await data.Password);

            if (dota_resp && await pb.collection('UserTable').authRefresh()) {
                cookies().set(pb.authStore.exportToCookie({httpOnly: true}), { secure: false })
                return {"success": JSON.stringify(pb.authStore)}
            }
            else{
                return{"failed": "something went wrong with with validation"}
            }
        }
        catch (error) {
            return { "failed": JSON.stringify(error) };
        }
    }
`
and i just manually setting authstore
` if (dependency.success) {
            setIsPending(false)
            const DataMutation = JSON.parse(dependency.success)
            const tok = await DataMutation.storageFallback.pocketbase_auth.token
            const mod = await DataMutation.storageFallback.pocketbase_auth.model
         
            pb.authStore.save(tok,mod)
            return router.push("/")
        }`
im trying to access cookie from middleware
`if (request.nextUrl.pathname.startsWith('/account')) {
    console.log(response.headers)

    
    if(await request.cookies.has("pb_auth")){
      return NextResponse.next()
    }
    else{
      return NextResponse.redirect(new URL('/', request.url))
    }
}
` 
im only beginner, but i think im missing something...

**Comment by ganigeorgiev** [comment] 2023-10-01 14:22
The following line doesn't seem correct:

```js
cookies().set(pb.authStore.exportToCookie({httpOnly: true}), { secure: false })
```

Per [Next.js documentation](https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options), the `set` signature seems to be either an object or `name, value, options` argument.

Additionally note that `pb.authStore.exportToCookie` generates a full serialized cookie string (name, value, options together).
If you are going to use the Next.js cookies abstraction then you don't have to use the `exportToCookie` method and can construct the cookie value on your own with something like (_I haven't tested it_):

```js
cookies().set({
    name: 'pb_auth',
    value: JSON.stringify({ token: pb.authStore.token }),
    httpOnly: true,
    sameSite: "strict",
    secure: true,
    path: '/',
})
```

---

As a side-note, I don't recommend using Next.js SSR, especially if you are not sure what you are doing, as the last time I checked it didn't have an ergonomic solution for sharing complex local data between middlewares/server-side components (see also https://github.com/pocketbase/js-sdk/issues/69).

**Comment by Marius555** [comment] 2023-10-01 14:37
ya, you can change cookie().set() but that doesnt solve the problem, my problem is that everything that i did works on my laptop, but why it doesnt work on mobile....i can get cookies from laptop but im geting 0 cookies from mobile

**Comment by emilio-toledo** [comment] 2024-07-25 01:55
> The following line doesn't seem correct:
> 
> ```js
> cookies().set(pb.authStore.exportToCookie({httpOnly: true}), { secure: false })
> ```
> 
> Per [Next.js documentation](https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options), the `set` signature seems to be either an object or `name, value, options` argument.
> 
> Additionally note that `pb.authStore.exportToCookie` generates a full serialized cookie string (name, value, options together). If you are going to use the Next.js cookies abstraction then you don't have to use the `exportToCookie` method and can construct the cookie value on your own with something like (_I haven't tested it_):
> 
> ```js
> cookies().set({
>     name: 'pb_auth',
>     value: JSON.stringify({ token: pb.authStore.token, model: pb.authStore.model }),
>     httpOnly: true,
>     sameSite: "strict",
>     secure: true,
>     path: '/',
> })
> ```
> 
> As a side-note, I don't recommend using Next.js SSR/RSC, especially if you are not sure what you are doing, as the last time I checked it didn't have an ergonomic solution for sharing complex local data between middlewares/server-side components (see also #69).

For anyone using PocketBase and Svelte, this way of setting cookies from a sveltekit action fixed the sign in issue that I had on IOS/Mobile.
