### ISSUE TITLE
Use exportToCookie but opt-out of serialization

### ISSUE THREAD

**Issue by sea-grass** [pocketbase/js-sdk#74] opened 2022-11-11 16:34 UTC
Hi there! I'm just getting started with pocketbase in a svelte-kit project. As you might know, svelte-kit is pre-1.0.0 and is subject to breaking changes, with the `cookies` interface being one of them. The pocketbase js-sdk readme shows how to integrate with svelte-kit's SSR: create the client, initialize the auth store with the request cookie, and at the end of the request update the cookie with the state of the auth store.

If you were to implement the example from the readme...

```js
// src/hooks.js
import PocketBase from 'pocketbase';

export async function handle({ event, resolve }) {
    event.locals.pocketbase = new PocketBase("http://127.0.0.1:8090");

    // load the store data from the request cookie string
    event.locals.pocketbase.authStore.loadFromCookie(event.request.headers.get('cookie') || '');

    const response = await resolve(event);

    // send back the default 'pb_auth' cookie to the client with the latest store state
    response.headers.set('set-cookie', event.locals.pocketbase.authStore.exportToCookie());

    return response;
}
```

You would encounter the error `TypeError: Failed to execute 'set' on 'Headers': Headers are immutable`. The workaround is to set the cookie using the cookies interface on the Handle event. The problem is that the `cookies.set` function has the signature `(name: string, value: string, opts: CookieSerializeOptions) => void`, while the auth store's `exportToCookie` function serializes the cookie and returns a string. This leads to a workaround where we need to deserialize the cookie from `exportToCookie` before using `cookies.set`:

```js
export async function handle({ event, resolve }) {
  // ...truncated

  const response = await resolve(event);

  // wasteful: exportToCookie serializes the cookie and then we must deserialize the cookie
  const authCookie = cookie.parse(client.authStore.exportToCookie());
  cookies.set('pb_auth', authCookie.pb_auth, {
    path: authCookie.Path,
    expires: new Date(authCookie.Expires),
    sameSite: 'strict',
  });
```

With that established, I guess there are two things here: the code example in the svelte-kit section of this repo's readme is broken and there's a workaround required to integrate with Svelte-Kit. For the second problem, where pocketbase serializes the cookie and in svelte-kit it's necessary to deserialize the cookie before setting it, I'm not sure where the fix is best suited. Should svelte-kit accept serialized cookie headers and handle them internally? Or should pocketbase expose an escape hatch to return the cookie before serializing it? In svelte-kit, the fix would add complexity to the internals for more work, while the pocketbase fix would add complexity to the API for less work. I personally am leaning towards the pocketbase escape hatch. Maybe a `pocketbase.authStore.exportToCookieRaw()`?

**Comment by ganigeorgiev** [comment] 2022-11-11 17:05
@sea-grass I'm not able to reproduce the "_TypeError: Failed to execute 'set' on 'Headers': Headers are immutable_" error.
In what version this was introduced? I've tested with the most recent one - `sveltejs/kit 1.0.0-next.543`.

_The only thing I had to change in the readme was `hooks.js` to `hooks.server.js` and adding `async` to the `+server.js` action but that is already updated in the `rc` branch - https://github.com/pocketbase/js-sdk/tree/rc_

**Comment by sea-grass** [comment] 2022-11-11 17:28
Thanks @ganigeorgiev. Let me see if I can reproduce in the latest kit. In my repo, I'm also using [trpc-sveltekit](https://github.com/icflorescu/trpc-sveltekit) so it's possible that it's the one marking response headers as immutable (in which case I'll have to determine if I'll ever need to update the auth store after trpc handles a request or if I should only set the cookie after kit handles a request). I'll dig a bit more and may link to a reproduction repo in a bit.

**Comment by ganigeorgiev** [comment] 2022-11-22 07:01
I'm closing the issue since I wasn't able to reproduce it.

In any case, I don't think it will be very useful to export the cookie without the key because it will be confusing to have only the cookie value + its attributes as a string. I'm not actually sure how in your example this even works, because the exported string is with cookie attributes while at the same time you are setting a custom ones (aka. `path`, `sameSite`, `expires`, etc.).

If you need only the cookie data value, you can just use:

```js
JSON.stringify({ token: client.authStore.token, model: client.authStore.model })
```

**Closed by ganigeorgiev** 2022-11-22 07:01 UTC
