### ISSUE TITLE
Error "EventSource connect took too long" in connecting in real time with react native + expo

### ISSUE THREAD

**Issue by wesleywcr** [pocketbase/js-sdk#257] opened 2023-11-13 02:46 UTC
I'm trying to make a real-time connection in a chat on my app. But I'm facing this problem with the connection:

`Error Subscribe: [Error: EventSource connect took too long.]
`
My code:
```js
 useFocusEffect(
    useCallback(() => {
      const fetchNewMessages = async () => {
        try {
          await pb.collection('messages').subscribe('*', (e) => {
            console.log('action', e.action);
            refetch();
          });
        } catch (error: any) {
          console.error('Error Subscribe', error.originalError);
        }
      };

      fetchNewMessages();

      return async () => {
        try {
          await pb.collection('messages').unsubscribe('*');
        } catch (error: any) {
          console.log('Error Unsubscribed', error.originalError);
        }
      };
    }, [refetch]),
  );
```

What can I do to make the real time functionality work correctly?

**Comment by ganigeorgiev** [comment] 2023-11-13 06:16
I'm not sure how to help you debug it but I don't think the issue is JS SDK related.

Double check that client can access to the PocketBase server.

Does regular requests works?

Where the above code is being executed - browser, servers-side, React Native?

I'll close the issue for now as there is no actionable item, but feel free to provide more details about your setup and ideally some minimal steps to reproduce, and I'll have a more look.

**Closed by ganigeorgiev** 2023-11-13 06:16 UTC

**Comment by ganigeorgiev** [comment] 2023-11-13 06:26
On second read, I missed that in the title is mentioned React Native.

In this case, you need a EventSource polyfill, for example `react-native-sse`:

```js
import eventsource from "react-native-sse";

global.EventSource = eventsource;
```

**Comment by ganigeorgiev** [comment] 2023-11-13 07:11
You could also check the comment in https://github.com/pocketbase/pocketbase/discussions/2484#discussioncomment-6118523.

**Comment by wesleywcr** [comment] 2023-11-14 02:36
I've already added `react-native-sse`, others requests in pocketbase work normally. Only the question of the real time that generates the above error.  Do I need to add another configuration to my project?

**Comment by ganigeorgiev** [comment] 2023-11-14 07:12
@wesleywcr Please check the linked resources in https://github.com/pocketbase/pocketbase/discussions/2484#discussioncomment-6118523.

If that doesn't help, please provide more details how you are testing and ideally create a **minimal** reproducible repo and I'll investigate it further.

**Comment by wesleywcr** [comment] 2023-11-16 11:57
It seems like it was a problem in the expo version. I was using SDK 49, I downgraded it to SDK 48 and worked normally.
