### ISSUE TITLE
Some Problem with having subscription right after init.

### ISSUE THREAD

**Issue by mmv-dev** [pocketbase/js-sdk#143] opened 2023-02-01 22:29 UTC
# I am using the latest version only v0.10.1

```
error - unhandledRejection: ReferenceError: EventSource is not defined
    at RealtimeService.initConnect (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35330)
    at file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35026
    at new Promise (<anonymous>)
    at RealtimeService.<anonymous> (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:34924)
    at step (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2088)
    at Object.next (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2193)
    at file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1103
    at new Promise (<anonymous>)
    at __awaiter (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:789)
    at RealtimeService.connect (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:34796)
error - unhandledRejection: ClientResponseError 0: Something went wrong while processing your request.
    at new ClientResponseError (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2285)
    at RealtimeService.connectErrorHandler (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:36727)        
    at Timeout.<anonymous> (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35214)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  url: '',
  status: 0,
  data: {},
  isAbort: false,
  originalError: Error: EventSource connect took too long.
      at Timeout.<anonymous> (file:///D:/Org/application/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35234)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node: internal/timers:502:7)
}
```

**Comment by ganigeorgiev** [comment] 2023-02-01 22:35
Hm, the above stacktrace contains 2 different errors:

- `unhandledRejection: ReferenceError: EventSource is not defined`

- `Error: EventSource connect took too long.`

I suspect the timeout error was triggered because of the first one.

Could you provide more information about your setup, eg. where your code runs (in the browser, in a node server handler or in react native), do you use a `EventSource` polyfill and if yes which one and how do you load it, etc.?

**Comment by ganigeorgiev** [comment] 2023-02-01 22:40
If your code runs in a node/react-native env, please check the notes in https://github.com/pocketbase/js-sdk#nodejs-via-npm.

**Comment by ganigeorgiev** [comment] 2023-02-02 07:50
@mmv-dev I'm closing the issue since I'm not able to reproduce it.

I suspect that it is caused by a missing `EventSource` polyfill. For an example how to load it you can check the nodejs/react-native notes in https://github.com/pocketbase/js-sdk#nodejs-via-npm.

If that's not the case, feel free to provide more details (and a sample code if possible) and I'll investigate it.

**Closed by ganigeorgiev** 2023-02-02 07:50 UTC
