### ISSUE TITLE
Access API in (Angular) SPA on same domain outside of routing interception.

### ISSUE THREAD

**Issue by slimcdk** [pocketbase/js-sdk#155] opened 2023-02-25 12:08 UTC
Hello folks

I'm really impressed with the quality of this project. I plan on serving Angular and PocketBase on same domain, where PocketBase's API will be accessible on `/api` however Angular's routing mechanism seem to intercept any calls to this path as navigation and not as calls to my backend server.

I'm initializing PocketBase in an Angular service that I inject throughout my application. So far this works fine as long as PocketBase is served on another domain/port. I suspect I somehow should be able to inject a or wrap the SDK in a `HttpClient` that Angular will use to make backend calls https://angular.io/guide/http. But how could this be done?

```typescript
export class PocketBaseService {

  readonly pb: PocketBase;

  constructor() {
    this.pb = new PocketBase(environment.apiHost);
  }
}
```

**Comment by ganigeorgiev** [comment] 2023-02-25 12:16
I'm not sure that I understand the issue and I don't see how it is related to the SDK.

Could you elaborate a little more on your setup? How are you deploying the Angular app? Is there a reverse proxy or you are using the static `pb_public` files serve that comes with PocketBase?

>  I suspect I somehow should be able to inject a or wrap the SDK in a HttpClient that Angular will use to make backend calls

I don't see why this will be needed. The SDK uses the native `fetch` for sending requests.

**Comment by ganigeorgiev** [comment] 2023-02-25 13:23
I'm not very up-to-date with the recent Angular development and I'm not sure what to recommend, but you may want to check https://angular.io/guide/build#proxying-to-a-backend-server in case it is relevant to your use case.

I'm closing the issue because I don't think is related to the SDK but feel free to provide more details about your setup (or a minimal reproducible repo if possible) and I'll try to investigate it in more details.

**Closed by ganigeorgiev** 2023-02-25 13:23 UTC

**Comment by slimcdk** [comment] 2023-02-25 15:10
I know this isn't necessarily an issue with this SDK, but I've been traversing through Angular documentation and Angular forums to find the solution and there seemingly isn't one. I'm not alone about this and I would imagine that existing PB user might have solved it so this is my last bullet in the chamber.

Angular intercepts all requests (for same domain) on the client and nothing is sent to the backend, unless you explicitly use the provided HttpClient. My eager hope was that you could inject your own http client. As long as it implements the needed interface. Very similar to the AuthStorage.

It might as well just be my setup that prevents Angular to forward request from the SDK to the backend instead of the routing mechanism. This is a typical (and minimal) routing configuration with wildcard routing to a 404 page.
```typescript
const routes: Routes = [
  { path: '', component: HomePageComponent },
  ...
  { path: '**', component: PageNotFoundComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  providers: []
})
```

The 'proxy to a backend server' unfortunate only works with the node runtime (primarly during development) and not if you do a production build with a static webserver like nginx, so this option is not available in production. Both PocketBase and Angular are running behind a reverse proxy (traefik) and Angular is being hosted from a nginx instance.

**Comment by ganigeorgiev** [comment] 2023-02-25 15:24
> Both PocketBase and Angular are running behind a reverse proxy (traefik) and Angular is being hosted from a nginx instance.

My guess is that you are using nginx to rewrite all routes to the static index.html, right?
If that's the case, instead of passing down every route to the angular app, you can make an exception and configure the reverse proxy to proxy_pass all `/api/*` routes to the backend server.

But without an actial traefik/nginx config sample how you are deploying your app, I'm not sure how to help.

If you need an example nginx config for PocketBase you can check https://pocketbase.io/docs/going-to-production/#using-reverse-proxy.

**Comment by ganigeorgiev** [comment] 2023-02-25 15:29
Additionally, please note for static client-side apps you don't really need nginx and you can put your files inside `pb_public` directory next to the executable (you can change the default public dir location with the `--publicDir` flag).

**Comment by slimcdk** [comment] 2023-02-25 15:33
I'm only using nginx as a static webserver. The issue is however that Angular does not send anything to the backend. So I can't even rewrite the routes on my reverse proxy. Requests from the PocketBase SDK gets intercepted by the Angular router, because they aren't performed by the Angular HttpClient.

I'm aware of the `pb_public` option but this sadly won't change how Angular and the SDK behaves on the client level. I can only imagine that if the SDK used Angulars HttpClient it would work, but I know that this isn't feasble for the SDK to adopt this. My workaround as of now is to simply server PB's API on a subdomain, but I feel it kind of inflicts with the email linking

**Comment by slimcdk** [comment] 2023-02-25 15:44
Apologies for the many edits.

**Comment by ganigeorgiev** [comment] 2023-02-25 16:22
> Requests from the PocketBase SDK gets intercepted by the Angular router, because they aren't performed by the Angular HttpClient.

But how? I can't find any reference in the Angular documentation for modified/overwritten `fetch`.

Your setup is too complicated and I'm not sure how to properly reproduce it.

I've tried:
1. Installed the basic setup from https://angular.io/guide/setup-local
2. Added a single route with a component that call PocketBase (not as a service but directly, but I doubt that this matter).
3. Executed `npm run build` to generate the static files
4. Moved the static files to a `pb_public` directory
5. Started PocketBase and clicked on the button of the component in 2) to test the API call and it worked fine.

**Comment by slimcdk** [comment] 2023-02-25 18:43
I found the culprit. It was the developer all along.. I had configured my reverse proxy to redirect on exact `/api` match and not as a prefix... Everything now works smoothly. Thanks again for this awesome project. And for your time trying to reproduce my issue even though it wasn't remotely related to this SDK.
