### ISSUE TITLE
Can't use pocketbase on React Native.

### ISSUE THREAD

**Issue by niputy** [pocketbase/js-sdk#114] opened 2022-12-22 16:57 UTC
Hey!
I tried to use pocketbase with React Native and get error:
`ClientResponseError 0: Something went wrong while processing your request.` 
Can someone please confirm that pocketbase is not working on React Native and it's possible to add support for React Native too?

**Comment by ganigeorgiev** [comment] 2022-12-24 07:29
@niputy I'm closing the issue since I'm not able to reproduce it (tested with Expo). Please provide the full error stack trace and/or a code sample how you initialize the SDK and what method calls you are making.

**Closed by ganigeorgiev** 2022-12-24 07:29 UTC

**Comment by niputy** [comment] 2022-12-24 09:23
Looks like it's http issue described [here](https://github.com/facebook/react-native/issues/32931). `console.log(err.originalError) `show `TypeError: Network request failed` 
I used latest versions of everything, you actually can test on my app [here](https://github.com/niputy/ChatApp).
It's possible to change pocketbase url from http to https?

**Comment by ganigeorgiev** [comment] 2022-12-24 09:37
> It's possible to change pocketbase url from http to https?

You can start the PocketBase executable with `--https="yourdomain.com:443"` but it'll issue a Let's encrypt certificate and expects a valid public domain (it will not work with bare IPs).

It is hard to debug what exactly is the issue since the error is too generic and there is no stack trace attached. Make sure that the your device have access to the PocketBase url address (in the code it is 127.0.0.1 but if you are running inside an emulator you have to use 10.0.2.2 per https://developer.android.com/studio/run/emulator-networking#networkaddresses).

**Comment by niputy** [comment] 2022-12-24 09:47
Omg, I just change 127.0.0.1 to 10.0.2.2 and now it's working. Thank you very much!
Issue was resolved.

**Comment by dannyvidal** [comment] 2023-04-10 12:00
I know its been a while but if anyone comes across this issue you can use ngrok. 
```
ngrok http 8090 
# Or whatever port you have pocketbase set to.
```
note: you do have to make an account but it is free.

**Comment by NoCluePS** [comment] 2023-11-27 17:51
@ganigeorgiev , so it's not possible to have realtime in react-native?

**Comment by ganigeorgiev** [comment] 2023-11-27 17:57
@NoCluePS I don't know how did you come to this conclusion.

It should work fine but you'll have to load a polyfill (see the note in https://github.com/pocketbase/js-sdk#nodejs-via-npm). Also if you are testing on Android in debug mode please check the linked resources in https://github.com/pocketbase/pocketbase/discussions/2484#discussioncomment-6118523.

If you are still not able to make it work, feel free to open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) in the main repo with more details about your setup and how are you testing and I'll try to investigate it.

**Comment by NoCluePS** [comment] 2023-11-27 18:05
Sorry, didn't refresh hard enough apparently :D

**Comment by iamveso** [comment] 2025-03-06 19:22
just to add to this discussion, if you're using expo and testing on your device with expo go, you should look at the IP displayed in your terminal by expo and use that instead of the IP pocketbase is running on locally.
